In [1]:
!pip install lifelines

Collecting lifelines
  Downloading lifelines-0.30.0-py3-none-any.whl.metadata (3.2 kB)
Requirement already satisfied: numpy>=1.14.0 in /usr/local/lib/python3.11/dist-packages (from lifelines) (1.26.4)
Requirement already satisfied: scipy>=1.7.0 in /usr/local/lib/python3.11/dist-packages (from lifelines) (1.14.1)
Requirement already satisfied: pandas>=2.1 in /usr/local/lib/python3.11/dist-packages (from lifelines) (2.2.2)
Requirement already satisfied: matplotlib>=3.0 in /usr/local/lib/python3.11/dist-packages (from lifelines) (3.10.0)
Requirement already satisfied: autograd>=1.5 in /usr/local/lib/python3.11/dist-packages (from lifelines) (1.7.0)
Collecting autograd-gamma>=0.3 (from lifelines)
  Downloading autograd-gamma-0.5.0.tar.gz (4.0 kB)
  Preparing metadata (setup.py) ... done
Collecting formulaic>=0.2.2 (from lifelines)
  Downloading formulaic-1.1.1-py3-none-any.whl.metadata (6.9 kB)
Collecting interface-meta>=1.2.0 (from formulaic>=0.2.2->lifelines)
  Downloading interface_meta-1.3.0-py3-none-any.whl.metadata (6.7 kB)
Requirement already satisfied: typing-extensions>=4.2.0 in /usr/local/lib/python3.11/dist-packages (from formulaic>=0.2.2->lifelines) (4.12.2)
Requirement already satisfied: wrapt>=1.0 in /usr/local/lib/python3.11/dist-packages (from formulaic>=0.2.2->lifelines) (1.17.2)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.0->lifelines) (1.3.1)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.0->lifelines) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.0->lifelines) (4.56.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.0->lifelines) (1.4.8)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.0->lifelines) (24.2)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.0->lifelines) (11.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.0->lifelines) (3.2.1)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.0->lifelines) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas>=2.1->lifelines) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas>=2.1->lifelines) (2025.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.7->matplotlib>=3.0->lifelines) (1.17.0)
Downloading lifelines-0.30.0-py3-none-any.whl (349 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 349.3/349.3 kB 8.1 MB/s eta 0:00:00
Downloading formulaic-1.1.1-py3-none-any.whl (115 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 115.7/115.7 kB 8.9 MB/s eta 0:00:00
Downloading interface_meta-1.3.0-py3-none-any.whl (14 kB)
Building wheels for collected packages: autograd-gamma
  Building wheel for autograd-gamma (setup.py) ... done
  Created wheel for autograd-gamma: filename=autograd_gamma-0.5.0-py3-none-any.whl size=4031 sha256=718cb0bf5917cc4592031c70c61247ebe6866fe9396b012319b4fb2273e52f05
  Stored in directory: /root/.cache/pip/wheels/8b/67/f4/2caaae2146198dcb824f31a303833b07b14a5ec863fb3acd7b
Successfully built autograd-gamma
Installing collected packages: interface-meta, autograd-gamma, formulaic, lifelines
Successfully installed autograd-gamma-0.5.0 formulaic-1.1.1 interface-meta-1.3.0 lifelines-0.30.0

In [8]:
# Kaplan-Meier Survival Curve
from lifelines import KaplanMeierFitter
from lifelines.utils import median_survival_times
import pandas as pd

# Read datafiles
train_file_path = "1yVTNHjwM4hUbv0alTfW9hEn1itOVbHLg"
test_file_path = "1-1NGzpvsdLcBPFZU_aNOZYn-1BIMoWO2"
train_url = f"https://drive.google.com/uc?export=download&id={train_file_path}"
test_url = f"https://drive.google.com/uc?export=download&id={test_file_path}"
train_df = pd.read_csv(train_url)
test_df = pd.read_csv(test_url)

# Instantiate KaplanMeierFitter
kmf = KaplanMeierFitter()

#Save  time variable(efs_time) in T and event/status variable (efs) in E
T = train_df["efs_time"]
E = train_df["efs"]

# Drop columns with high collinearity
train_df = train_df.drop('gvhd_proph_FK+- others(not MMF,MTX)', axis=1)

# Fit the Kaplan-Meier model
kmf.fit(durations=T, event_observed=E)

# Print Median Survival Time and Confidence Intervals
median_ = kmf.median_survival_time_
median_confidence_interval_ = median_survival_times(kmf.confidence_interval_)

print(f"Median Survival Time: {median_:.2f} months")
print(f"95% Confidence Interval for Median Survival Time: {median_confidence_interval_}")

'''
Interpretation:
- You can be 95% confident that the true median survival time for the population lies between 9.664 and 10.31 months.
- If you were to repeat the study with different samples, 95% of those samples would show a median survival time within this range.
'''

# Cox Proportional Hazards Model
from lifelines import CoxPHFitter

# Instantiate CoxPHFitter with a penalizer for Lasso regularization
cph = CoxPHFitter(penalizer=0.1)

# Fit the Cox model on the training data
cph.fit(train_df, duration_col='efs_time', event_col='efs')

# Print the CoxPH model summary
cph.print_summary()

'''
Interpretation:
- The Cox Proportional Hazards model can help us understand the relationship between covariates (e.g., age, treatment type) and survival.
- The coefficients in the summary will tell us the direction and strength of the relationship between each covariate and the risk of an event occurring (death, relapse, etc.).
'''

Median Survival Time: 9.98 months
95% Confidence Interval for Median Survival Time:      KM_estimate_lower_0.95  KM_estimate_upper_0.95
0.5                   9.664                   10.31

<lifelines.CoxPHFitter: fitted with 28800 total observations, 13268 right-censored observations>
             duration col = 'efs_time'
                event col = 'efs'
                penalizer = 0.1
                 l1 ratio = 0.0
      baseline estimation = breslow
   number of observations = 28800
number of events observed = 15532
   partial log-likelihood = -151836.60
         time fit was run = 2025-03-12 05:45:48 UTC

---
                                                      coef exp(coef)  se(coef)  coef lower 95%  coef upper 95% exp(coef) lower 95% exp(coef) upper 95%
covariate
ID                                                   -0.00      1.00      0.00           -0.00            0.00                1.00                1.00
dri_score                                             0.04      1.04      0.00            0.03            0.05                1.03                1.05
psych_disturb                                         0.03      1.03      0.01            0.00            0.05                1.00                1.05
cyto_score                                            0.03      1.03      0.00            0.03            0.04                1.03                1.04
diabetes                                              0.02      1.02      0.01           -0.01            0.04                0.99                1.04
hla_match_c_high                                     -0.02      0.98      0.01           -0.05           -0.00                0.96                1.00
hla_high_res_8                                        0.00      1.00      0.00           -0.00            0.01                1.00                1.01
arrhythmia                                            0.01      1.01      0.01           -0.02            0.03                0.98                1.03
hla_low_res_6                                         0.01      1.01      0.01            0.00            0.03                1.00                1.03
graft_type                                            0.09      1.10      0.03            0.04            0.14                1.04                1.15
vent_hist                                            -0.01      0.99      0.03           -0.06            0.05                0.94                1.06
renal_issue                                          -0.02      0.98      0.01           -0.05            0.01                0.95                1.01
pulm_severe                                           0.01      1.01      0.01           -0.01            0.04                0.99                1.04
hla_high_res_6                                        0.00      1.00      0.01           -0.01            0.01                0.99                1.01
cmv_status                                            0.02      1.02      0.01            0.01            0.03                1.01                1.03
hla_high_res_10                                       0.01      1.01      0.01           -0.01            0.02                0.99                1.02
hla_match_dqb1_high                                   0.01      1.01      0.02           -0.04            0.06                0.96                1.06
hla_nmdp_6                                           -0.03      0.97      0.01           -0.05           -0.01                0.95                0.99
hla_match_c_low                                      -0.04      0.96      0.03           -0.09            0.02                0.91                1.02
rituximab                                             0.04      1.04      0.05           -0.06            0.14                0.94                1.15
hla_match_drb1_low                                    0.02      1.02      0.03           -0.03            0.08                0.97                1.08
hla_match_dqb1_low                                    0.02      1.02      0.02           -0.03            0.06                0.97                1.07
cyto_score_detail                                     0.08      1.08      0.01            0.07            0.09                1.07                1.09
conditioning_intensity                                0.06      1.07      0.00            0.06            0.07                1.06                1.08
year_hct                                             -0.03      0.97      0.00           -0.03           -0.02                0.97                0.98
mrd_hct                                              -0.08      0.92      0.01           -0.11           -0.06                0.90                0.94
in_vivo_tcd                                          -0.07      0.93      0.02           -0.10           -0.04                0.90                0.97
tce_match                                            -0.01      0.99      0.01           -0.03            0.01                0.97                1.01
hla_match_a_high                                     -0.04      0.96      0.01           -0.07           -0.02                0.94                0.98
hepatic_severe                                       -0.07      0.93      0.02           -0.12           -0.03                0.89                0.97
donor_age                                             0.00      1.00      0.00            0.00            0.00                1.00                1.00
prior_tumor                                           0.01      1.01      0.02           -0.03            0.04                0.97                1.04
hla_match_b_low                                       0.04      1.04      0.01            0.01            0.06                1.01                1.06
peptic_ulcer                                         -0.02      0.98      0.03           -0.08            0.03                0.93                1.03
age_at_hct                                            0.00      1.00      0.00            0.00            0.00                1.00                1.00
hla_match_a_low                                      -0.02      0.98      0.01           -0.05            0.00                0.96                1.00
rheum_issue                                          -0.03      0.97      0.03           -0.09            0.02                0.92                1.02
sex_match                                             0.09      1.09      0.01            0.08            0.10                1.08                1.11
hla_match_b_high                                     -0.03      0.97      0.01           -0.05           -0.01                0.95                0.99
comorbidity_score                                     0.07      1.07      0.00            0.06            0.08                1.06                1.08
karnofsky_score                                      -0.01      0.99      0.00           -0.01           -0.00                0.99                1.00
hepatic_mild                                         -0.00      1.00      0.01           -0.03            0.02                0.98                1.02
hla_low_res_8                                        -0.02      0.98      0.01           -0.04            0.00                0.96                1.00
hla_match_drb1_high                                   0.07      1.07      0.01            0.04            0.09                1.04                1.09
hla_low_res_10                                       -0.00      1.00      0.01           -0.02            0.02                0.98                1.02
tbi_status_No TBI                                    -0.06      0.94      0.03           -0.12           -0.01                0.89                0.99
tbi_status_TBI + Cy +- Other                          0.06      1.06      0.03            0.01            0.12                1.01                1.13
tbi_status_TBI +- Other, -cGy, fractionated          -0.10      0.90      0.12           -0.34            0.13                0.71                1.14
tbi_status_TBI +- Other, -cGy, single                -0.21      0.81      0.11           -0.43            0.02                0.65                1.02
tbi_status_TBI +- Other, -cGy, unknown dose           0.13      1.14      0.15           -0.15            0.42                0.86                1.52
tbi_status_TBI +- Other, <=cGy                        0.15      1.16      0.04            0.08            0.22                1.08                1.25
tbi_status_TBI +- Other, >cGy                        -0.07      0.93      0.04           -0.15            0.00                0.86                1.00
tbi_status_TBI +- Other, unknown dose                 0.15      1.16      0.14           -0.13            0.43                0.88                1.54
prim_disease_hct_AI                                   0.21      1.23      0.06            0.08            0.33                1.09                1.39
prim_disease_hct_ALL                                  0.13      1.13      0.02            0.08            0.18                1.08                1.19
prim_disease_hct_AML                                  0.09      1.10      0.03            0.04            0.14                1.04                1.15
prim_disease_hct_CML                                  0.49      1.63      0.27           -0.04            1.01                0.96                2.75
prim_disease_hct_HD                                  -0.65      0.52      0.26           -1.16           -0.14                0.31                0.87
prim_disease_hct_HIS                                 -0.55      0.58      0.09           -0.72           -0.37                0.49                0.69
prim_disease_hct_IEA                                 -0.35      0.70      0.05           -0.45           -0.25                0.64                0.78
prim_disease_hct_IIS                                 -0.39      0.68      0.06           -0.51           -0.28                0.60                0.76
prim_disease_hct_IMD                                 -0.09      0.92      0.13           -0.35            0.17                0.71                1.19
prim_disease_hct_IPA                                  0.05      1.05      0.04           -0.02            0.12                0.98                1.13
prim_disease_hct_MDS                                  0.01      1.01      0.03           -0.05            0.07                0.96                1.08
prim_disease_hct_MPN                                  0.02      1.02      0.04           -0.05            0.09                0.95                1.10
prim_disease_hct_NHL                                 -0.01      0.99      0.04           -0.09            0.07                0.92                1.07
prim_disease_hct_Other acute leukemia                -0.11      0.90      0.15           -0.41            0.19                0.67                1.21
prim_disease_hct_Other leukemia                      -0.19      0.83      0.08           -0.34           -0.03                0.71                0.97
prim_disease_hct_PCD                                 -0.19      0.83      0.06           -0.29           -0.08                0.74                0.92
prim_disease_hct_SAA                                 -0.09      0.91      0.06           -0.21            0.02                0.81                1.02
prim_disease_hct_Solid tumor                         -0.09      0.91      0.10           -0.29            0.11                0.75                1.11
obesity_No                                           -0.02      0.98      0.04           -0.10            0.06                0.90                1.06
obesity_Not done                                     -0.01      0.99      0.05           -0.10            0.09                0.90                1.09
obesity_Yes                                           0.05      1.05      0.05           -0.04            0.14                0.96                1.15
tce_imm_match_G/B                                     0.01      1.01      0.06           -0.11            0.12                0.90                1.13
tce_imm_match_G/G                                    -0.04      0.96      0.04           -0.11            0.03                0.89                1.03
tce_imm_match_H/B                                     0.07      1.07      0.09           -0.10            0.23                0.90                1.26
tce_imm_match_H/H                                    -0.12      0.88      0.05           -0.22           -0.03                0.80                0.97
tce_imm_match_P/B                                    -0.16      0.85      0.17           -0.50            0.18                0.61                1.19
tce_imm_match_P/G                                     0.13      1.13      0.23           -0.33            0.58                0.72                1.78
tce_imm_match_P/H                                    -0.11      0.89      0.14           -0.39            0.17                0.68                1.18
tce_imm_match_P/P                                     0.01      1.01      0.03           -0.05            0.06                0.95                1.06
tce_imm_match_Unknown                                 0.02      1.03      0.03           -0.03            0.08                0.97                1.08
prod_type_BM                                         -0.06      0.94      0.03           -0.13           -0.00                0.88                1.00
prod_type_PB                                          0.06      1.07      0.03            0.00            0.13                1.00                1.14
ethnicity_Hispanic or Latino                          0.03      1.03      0.04           -0.05            0.11                0.95                1.12
ethnicity_Missing                                    -0.06      0.94      0.06           -0.18            0.06                0.83                1.06
ethnicity_Non-resident of the U.S.                   -0.08      0.93      0.08           -0.23            0.08                0.80                1.08
ethnicity_Not Hispanic or Latino                     -0.01      0.99      0.04           -0.08            0.07                0.92                1.07
race_group_American Indian or Alaska Native          -0.02      0.98      0.03           -0.07            0.03                0.93                1.03
race_group_Asian                                     -0.02      0.98      0.03           -0.07            0.04                0.93                1.04
race_group_Black or African-American                  0.12      1.12      0.03            0.06            0.17                1.07                1.18
race_group_More than one race                        -0.09      0.92      0.03           -0.14           -0.04                0.87                0.96
race_group_Native Hawaiian or other Pacific Islander -0.03      0.97      0.03           -0.08            0.02                0.92                1.02
race_group_White                                      0.04      1.04      0.03           -0.01            0.09                0.99                1.10
tce_div_match_Bi-directional non-permissive          -0.13      0.88      0.06           -0.25           -0.01                0.78                0.99
tce_div_match_GvH non-permissive                     -0.06      0.94      0.04           -0.13            0.02                0.88                1.02
tce_div_match_HvG non-permissive                      0.00      1.00      0.04           -0.08            0.09                0.92                1.09
tce_div_match_Permissive mismatched                  -0.00      1.00      0.03           -0.05            0.05                0.95                1.05
tce_div_match_Unknown                                 0.03      1.03      0.03           -0.03            0.09                0.98                1.09
donor_related_Multiple donor (non-UCB)               -0.06      0.94      0.07           -0.20            0.09                0.81                1.09
donor_related_Related                                -0.06      0.94      0.03           -0.12           -0.00                0.89                1.00
donor_related_Unrelated                               0.06      1.06      0.03            0.01            0.12                1.01                1.13
melphalan_dose_MEL                                    0.01      1.01      0.03           -0.06            0.07                0.95                1.07
melphalan_dose_N/A, Mel not given                    -0.01      0.99      0.03           -0.07            0.06                0.93                1.06
cardiac_No                                           -0.03      0.97      0.04           -0.11            0.04                0.90                1.04
cardiac_Not done                                     -0.20      0.82      0.11           -0.42            0.02                0.66                1.02
cardiac_Unknown                                      -0.09      0.91      0.04           -0.18           -0.00                0.84                1.00
cardiac_Yes                                           0.25      1.28      0.04            0.16            0.33                1.17                1.40
pulm_moderate_No                                     -0.02      0.98      0.03           -0.08            0.04                0.93                1.05
pulm_moderate_Not done                               -0.05      0.95      0.10           -0.26            0.15                0.77                1.16
pulm_moderate_Unknown                                -0.06      0.94      0.04           -0.14            0.03                0.87                1.03
pulm_moderate_Yes                                     0.05      1.05      0.03           -0.01            0.11                0.99                1.12
gvhd_proph_CDselect +- other                         -0.20      0.82      0.20           -0.59            0.19                0.56                1.21
gvhd_proph_CDselect alone                            -0.14      0.87      0.09           -0.32            0.04                0.73                1.04
gvhd_proph_CSA + MMF +- others(not FK)                0.03      1.03      0.03           -0.04            0.10                0.96                1.10
gvhd_proph_CSA + MTX +- others(not MMF,FK)           -0.07      0.94      0.09           -0.25            0.12                0.78                1.12
gvhd_proph_CSA +- others(not FK,MMF,MTX)             -0.04      0.96      0.33           -0.68            0.60                0.51                1.83
gvhd_proph_CSA alone                                 -0.15      0.86      0.10           -0.36            0.05                0.70                1.05
gvhd_proph_Cyclophosphamide +- others                -0.14      0.87      0.03           -0.21           -0.08                0.81                0.93
gvhd_proph_Cyclophosphamide alone                    -0.05      0.95      0.03           -0.11            0.00                0.90                1.00
gvhd_proph_FK+ MMF +- others                          0.13      1.14      0.02            0.09            0.18                1.09                1.20
gvhd_proph_FK+ MTX +- others(not MMF)                 0.01      1.01      0.03           -0.04            0.06                0.96                1.07
gvhd_proph_FKalone                                    0.05      1.05      0.04           -0.04            0.14                0.96                1.15
gvhd_proph_No GvHD Prophylaxis                       -0.13      0.87      0.09           -0.30            0.04                0.74                1.04
gvhd_proph_Other GVHD Prophylaxis                    -0.13      0.88      0.06           -0.25           -0.01                0.78                0.99
gvhd_proph_Parent Q = yes, but no agent               0.27      1.31      0.15           -0.02            0.56                0.98                1.75
gvhd_proph_TDEPLETION +- other                       -0.16      0.85      0.07           -0.29           -0.03                0.75                0.97

'\nInterpretation:\n- The Cox Proportional Hazards model can help us understand the relationship between covariates (e.g., age, treatment type) and survival.\n- The coefficients in the summary will tell us the direction and strength of the relationship between each covariate and the risk of an event occurring (death, relapse, etc.).\n'